setup.py, vivarium/core/composition.py, vivarium/core/registry.py, vivarium/processes/nonspatial_environment.py
This PR brings the ```nonspatial_environment``` and ```timeline``` processes back into ```composition.py```. Pytests are not all passing because of a registry exception that we've been seeing independently in ```vivarium-cell```: 
<pre>Exception: registry already contains an entry for timeline: <class 'vivarium.processes.timeline.TimelineProcess'>></pre>
=> bring nonspatial environment and timeline back

release.sh, setup.py
To create a release for version 1.2.3 using the release script:
```console
./release.sh 1.2.3
```
The script checks that:
* Your working directory is clean (so that the git tag and PyPI versions match)
* You are on master (so that the version history is linear)
* The version in `setup.py` matches the script argument (so that you don't release a version without updating `setup.py`)
Then, the script:
* Creates a git tag with the version number and pushes the tag to GitHub
* Publishes the version to PyPI
=> Release 0.0.12 and Release Script

setup.py, vivarium/core/experiment.py, vivarium/processes/nonspatial_environment.py
In running some chemotaxis experiments, I came across a bug in which the environment attempts to update an agent that has already been deleted.  The ```schema_topology``` in ```Store``` uses ```node = self.get_path(path)``` with this agent's path, and retrieves a ```None```. As a partial fix, I have it skip the update if the node is ```None```. Though with this fix, the environment still continues to try updating the agent for the remained of the experiment. Maybe we should check if a node has been marked as deleted and update the environment's subschema?
=> [WIP] bug with node=None in schema_topology

setup.py, vivarium/core/experiment.py
We were calling `apply_subschemas` and `apply_defaults` as a kind of bludgeon across every inner of a given node (and all of their inners etc etc etc) each time we added a single element with `_add`, `_generate` and `_divide`.... needless to say this introduced a large amount of unneeded computation, especially if the subtree was large. Thanks to running ecoli models with realistic state we now have large subtrees, which revealed this problem. 
After this change subschemas are applied with surgical accuracy! Runtime is greatly improved.
All tests pass in `-core`, `-cell`, `-chemotaxis` and `-ecoli`, so I assume this works, though I would like to make some general tests for various subschema situations at some point to make sure we aren't missing any cases.
=> Apply subschema to only paths that have been added

vivarium/core/experiment.py, vivarium/library/dict_utils.py
While testing support for creating topologies with partial name overrides (in anticipation of the `vivarium-bioscrape` workshop) I found a couple oversights in the `inverse_topology` implementation:
* If the update had values that weren't explicitly alongside a topology with a `_path` specification, the updates for those values were dropped.
* If the update had multiple different ports that mapped to the same key in the topology, only the last updates would be kept. 
I fixed these issues and made a more comprehensive test for `inverse_topology` to ensure this behavior is maintained. Several asserts were added. Tests again are crucial here, especially for edge cases like this and more subtle topology behaviors.
=> Inverse topology fixes and tests

setup.py, vivarium/core/emitter.py, vivarium/core/process.py
In `vivarium-scripts`, we want to be able to upload and download experiment data for archival. This adds support for these operations.
=> Support Upload and Download Scripts

doc/reference/api/vivarium.processes.rst, doc/reference/api/vivarium.rst, vivarium/__init__.py, vivarium/core/composition.py, vivarium/core/experiment.py, vivarium/processes/derive_concentrations.py, vivarium/processes/disintegrate.py, vivarium/processes/exchange_a.py, vivarium/processes/meta_division.py, vivarium/processes/swap_compartment.py, vivarium/processes/swap_processes.py
This process can be used to remove a compartment when the state under its ```'trigger'``` port is set to ```True```. It can probably be extended to release its state into its outer for a more comprehensive disintegration.
Also added in this PR: ```compartment_hierarchy_experiment``` is a new function in ```composition.py``` that lets you specify experiments with arbitrarily embedded compartments, and under any keys.  This is used for a new test in ```meta_division```.
=> Disintegrate process

vivarium/processes/tree_mass.py
This adds a test for TreeMass. I will be using a similar process to calculate mass in ```vivarium-ecoli```, which might require some changes to the ```_reduce``` update method in experiment. This test will help guarantee that those changes don't alter essential function.
=> TreeMass test

vivarium/core/composition.py
This lets us put the timeline process at the environment level for experiments created with `agent_environment_experiment`
=> Allow specifying timeline in agent_environment_experiment

vivarium/core/experiment.py, vivarium/core/process.py, vivarium/library/topology.py
This PR gives ```Generator``` an ```initial_state``` method the merges the initial state of all its processes. This uses the ```inverse_topology``` function that was previously in ```experiment.py``` to map each process' schema to the composite's store structure. Many stand-alone functions from ```experiment.py``` which were associated with ```inverse_topology``` also had to be moved to ```process.py``` to avoid circular updates.
=> Generator initial state

setup.py, vivarium/core/experiment.py, vivarium/library/schema.py, vivarium/library/topology.py, vivarium/processes/burst.py, vivarium/processes/engulf.py, vivarium/processes/meta_division.py, vivarium/processes/remove.py, vivarium/processes/swap_processes.py
In the process of implementing the Engulf and Burst processes, we had a realization that some confusion was arising from using paths, which are topology-relative, from inside processes, which are topology agnostic. This was leading to process configurations that modified or appended the paths, which is actually what the topology is supposed to be doing for us in the first place. 
This PR modifies all of the tree update operations to use `key` instead of `path` for their targets, which point to keys directly residing in the target ports, and updates everywhere in this repository that invokes these updates to align to the new approach. This means all path specifications will come from assigning topologies to process ports, instead of processes having to know anything about paths (which is …
=> Tree updates take keys, not paths

vivarium/core/process.py
This PR is makes fixes that help `vivarium-cell` replace the updater `port_mapping` requirements from some processes. 
`generate_derivers` now uses default port names for the stores, and then applies `port_mapping` (a different `port_mapping` from the one of the previous sentence) to override those names. So derivers can have ports not declared by the processes that require them.
=> deriver ports

doc/conf.py, vivarium/plots/topology.py
This tool is great for productivity! It draws the Process + Store topology network.
This PR tunes the rendering, mainly to show Stores using the standard flowchart symbol for data stores. The trick is to construct a matplotlib `Path` and let `draw_networkx_nodes(node_shape=s)` pass it to `ax.scatter(marker=s)`.
Labels are bigger and `..` draws as ⬆︎.
=> Improve the topology grapher

mypy.ini, vivarium/core/process.py, vivarium/processes/growth_rate.py
This PR introduces a generic `growth_rate` process that applies exponential growth to a list of variables. It also includes optional growth rate noise. Each variable can have its own dynamic `growth_rate` and`growth_rate_noise` under the `rates` port -- these are set to `default_growth_rate` and `default_growth_rate_noise` parameters by default.
=> growth_rate

vivarium/core/experiment.py
This PR fixes #54. The bug was that when using inverting the topology to apply an update, with a topology that included a '..', the `store.apply_update()` was not reading '..' correctly and skipped the update. The addition of this line to `apply_update` fixed it:
```
if key == '..':
self.outer.apply_update(value, state)
```
This PR also extends the `test_complex_topology` pytest to include this configuration and assert that the update is applied.
=> fix complex topology bug

mypy.ini, vivarium/__init__.py, vivarium/processes/mass_adaptor.py
This PR brings in the mass adaptors @WilliamIX developed for the BioscrapeCOBRA composite. These are general adaptor derivers, which can be reused for many different projects. `MassToConcentration` converts mass (e.g. *fg*) to concentration (e.g. *mmolar*), and `MassToCount` converts mass to counts using a molecular weight. The characteristic units can be set upon initialization with parameters such as `output_concentration_units`.
=> mass adaptors

vivarium/plots/topology.py
@WilliamIX -- check this out! Feedback is welcome on the PR.
This PR updates the topology plot with additional options.
This include a "horizontal" `graph_format` setting that places processes above stores in two rows. This is now the default output.
There is also a new `process_colors` and `store_colors` option to set specific colors for each node: 
And a "hierarchy" `graph_format` option for separating levels of the store hierarchy:
=> Topology plot

vivarium/core/emitter.py, vivarium/core/experiment.py, vivarium/core/process.py, vivarium/library/units.py, vivarium/plots/topology.py
This change simplifies the code, and allows multiple nodes to be given the same label. The labeling only happens at the very end, upon plotting. So node ids assume the original node name for all other functions.
=> improve node_labels in topology plot

setup.py, vivarium/plots/topology.py
This PR adds a new keyword to the plot_topology function: custom_widths, which allow each process or store to have custom widths when plotted via networkx.
=> custom widths in topology plots

vivarium/core/store.py
Currently if the updater for an update ever ends up being `None`, it fails with a cryptic message about not being able to apply None as a function. This PR detects the failure and provides useful information about what went wrong: 
* the path to this node
* its current value
* what the update is that was trying to be applied, but whose updater is `None` for whatever reason. 
Beyond this case I think this is a general usability principle, that we should be on the lookout for cryptic failures that take awhile to figure out (especially things deep inside store) and figure out a way to provide more information to the user about what might be going wrong (!)
=> Provide information about update failure

mypy.ini, vivarium/core/emitter.py, vivarium/core/experiment.py, vivarium/experiments/large_database_experiment.py, vivarium/experiments/test_experiments.py
This PR fixes `Experiment's` `emit_configuration` method to better check the size of the emitted configuration, and remove all process parameters if it is too large for pymongo. I also added a new `large_database_experiment` file that makes an experiment with bunch of processes with random parameters, and emits them to the simulation database.
=> Experiment emitter config test

mypy.ini, vivarium/processes/division.py
`divide_condition` and `meta_division` are always used together, so here we introduce a single `division` process that does the job of both the previous processes. Additionally, this has a configurable `condition_function` that can be used to define any function to trigger division. It defaults to the same threshold function that was used in `divide_condition`.
=> division process

vivarium/core/process.py, vivarium/experiments/composite_merge.py, vivarium/library/datum.py
`Composite` had an interesting bug in which after a composite was initialized and merged into the class `Composite` was holding onto the `self.processes` and `self.topology` of the prior composite. So when a new composite was created, it had those processes. The PR fixes that by making a new `defaults` dict within `Datum`'s `__init__`. Also, `Composite` has new immutable defaults that get generated in `Datum`.
=> Composite debug

vivarium/composites/toys.py, vivarium/core/process.py, vivarium/core/types.py, vivarium/library/topology.py
This reverts #48. We have another branch being worked on that improves Vivarium's API, in a way similar to what was done in #48. The string-based paths for composers added in #48 just add unnecessary complexity.
=> Revert string paths

vivarium/core/store.py
Vivarium-core needs to provide more warning and exception messages when expectations are not met. Users should not have to use a debugger within this library, and ideally all of their errors will get appropriate messages to help them fix the problem.
To start, I added a ValueError when `Store's` `apply_update` fails to run the line `self.value = updater(self.value, update)`. The message provides the path at which this happens, and the update received.
=> Exception messages

vivarium/core/control.py
This adds more options to declaring control experiments, plots, and workflows. If strings, they are looked up in the `self.experiment_library` or `self.plot_library`.  If dicts, they can have either `'name'` keys for looking up in libraries, or `'plot'`/`'experiment'` keys for getting the functions directly.  Pytests pass unchanged, so all previous `Control` instances should be compatible.
=> Control improve

.pylintrc, mypy.ini, vivarium/library/wrappers.py
This PR introduces the `make_logging_process` function in `vivarium.library.wrappers`, which was developed originally in vivarium-ecoli. The function takes a subclass of Process, and returns a new subclass that automatically logs its update at each timestep to a new port (`"log_update"` by default).
This is achieved by making a new subclass of the given Process class on-the-fly. For instance, make_logging_process(TfBinding) returns a new class Logging_TfBinding which inherits from TfBinding, and behaves exactly the same except that it automatically logs its own updates. This general approach allows arbitrary processes to be automatically logged while writing minimal new code.
=> Logging updates from processes

vivarium/core/composer.py, vivarium/core/store.py, vivarium/experiments/store_api.py
This PR enhances the Store API changes introduced in #84. This includes requiring explicit `.create()` to make new stores at a path, and `.connect()` for connecting ports. We found that it is best if the API aligns with the mental model of the bigraph, even if it means more complicated syntax. By calling `.connect()` the user will have to recognize that it is working with processes and ports, and `.create()` will keep them from creating unintended stores.
Here is an example of the api:
```
store = Store({})  # create the root
store.create(['top', 'process1'], ToyProcess({}))  # create a process at a path
store.create(['top', 'process2'], ToyProcess({}))  # create another process at a path
store['top'].create('store2')  # create a new store at a path
store['top', …
```
=> API improvements and simple divide

vivarium/core/emitter.py, vivarium/core/engine.py, vivarium/core/experiment.py, vivarium/experiments/large_database_experiment.py
Some emits -- either of data or configurations -- can exceed mongoDB's 16MB document size limit. This PR aims to break those emits into smaller chunks and send them individually.
=> Break up emits into smaller chunks

vivarium/core/composition.py, vivarium/core/engine.py, vivarium/experiments/glucose_phosphorylation.py, vivarium/experiments/store_api.py
This PR subtly changes the `Engine` API to use function arguments rather than a big `config` dictionary. This is cleaner-looking, and shows up on editors for easy autocomplete and type hints. It unfortunately breaks previous API, but better to make the change now rather than after the paper is published and people begin using Vivarium.
=> Engine kwargs

vivarium/core/store.py
This change allows vivarium-ecoli to have an initial state that is derived from vivarium-ecoli data, so that tolist is not called on a list and thus does not crash the simulation.
=> Prevents tolist serializer on a list.

CHANGELOG.md, vivarium/core/engine.py
A request by @Robotato. This PR adds a `metadata` keyword arg to engine, and emits it in `Engine.emit_configuration`.
=> metadata kwarg for Engine

CHANGELOG.md, setup.py, vivarium/core/store.py
In Engine, we use `vivarium.core.store.generate_state()` to generate `Engine.state`. In vivarium-core==0.3.14, `store.generate_state()` worked like this:
```python
store = Store({})
store.generate_paths(processes, topology)
store.apply_subschemas()
store.set_value(initial_state)
store.apply_defaults()
return store
```
Notice that it applies the subschemas before setting values using `initial_state`.
In vivarium-core==0.4.0, I wanted to make `Store.generate_paths()` private, so I did this instead for `store.generate_state():`
```python
store = Store({})
steps = steps or {}
store.generate(tuple(), processes, steps, flow, topology, initial_state)
return store
```
I thought that this would work the same way as before, but `Store.generate()` looks like this:
```python
target = …
```
=> Fix Store.generate() to let initial state override _value in schemas

.gitignore, doc/requirements.txt, requirements.txt, setup.py, vivarium/core/engine.py, vivarium/core/process.py, vivarium/core/store.py
Profiling of `vivarium-ecoli` revealed that major time savings can be had by reducing the amount of time spent in the `schema_topology` function. One way to accomplish this is by caching the topology so that it does not have to be filled in again for timesteps where it does not change.
Here is a rudimentary caching implementation that only works if the topology never changes. I played around with `functools.lru_cache`, but it doesn't work OOTB because dictionaries are an unhashable type.
=> Implement Topology Caching

vivarium/core/engine.py, vivarium/core/store.py
This fixes a bug introduced in #96, in which `Store. schema_topology` returned an empty dict if a schema used the glob schema key `'*'`. I solved this by returning `self` instead of `{}`, so that the engine could use `view_values` to access the inner states.
=> schema_topology * returns self

vivarium/core/emitter.py, vivarium/core/engine.py
This adds a `query` argument to `get_history_data_db`, which lets you selectively query embedded fields within a saved experiment. This can result in much faster, selective emitter queries.
=> Query database

vivarium/composites/toys.py, vivarium/core/composer.py, vivarium/core/engine.py, vivarium/core/store.py, vivarium/core/types.py, vivarium/library/topology.py
This PR isolates and aims to fix some errors found in vivarium-notebooks resulting from the `Store.topology_view` caching introduced in #96.
=> Fix topology_view errors found in vivarium-notebooks

vivarium/__init__.py, vivarium/core/registry.py
This copies over the `dictionary_updater` developed in vivarium-ecoli by @thalassemia and @Robotato. This new updater translates `'_add'` and `'_delete'` -style updates into operations on a dictionary.
=> dictionary updater

vivarium/core/registry.py, vivarium/core/store.py, vivarium/library/dict_utils.py
When applying the divided values of both daughter cells to the default `initial_state` to get the new initial states, we were modifying `initial_state` in place, making it so the daughters shared the same dictionaries in memory for their values even when they had different stores. To get around this, I used `copy.deepcopy(initial_state)` since `dict(initial_state)`, which is recommended by the `deep_merge` function definition, is only a shallow copy, and thus creates the same issue of shared dictionaries.
=> Initial state is not modified when dividing cell.

CHANGELOG.md, setup.py, vivarium/core/engine.py, vivarium/core/process.py, vivarium/experiments/test_profiler.py
If you set `profile=True` in the `Engine` constructor, then when you call `Engine.end()`, Vivarium will compute profile statistics and store them in `Engine.stats` for you to analyze. The Engine also profiles parallel processes and includes those stats in `Engine.stats`, giving you a full picture of what's taking up runtime in your simulation.
See `vivarium/experiments/test_profile.py` for an example of how to use this.
=> Let Vivarium Engine Profile (including parallel processes)

CHANGELOG.md, setup.py
When I bumped the version in #113, I missed that the version had already been bumped to v0.4.8 by another PR. This PR fixes my mistake by bumping the version up again to v0.4.9
=> Fix version for parallel profile PR

vivarium/core/control.py
This allows you to pass options  to experiments with `run_library_cli`, using `-o key=value`
For example:
```
python vivarium/experiments/engine_tests.py -n 16 -o profile=False
```
=> add options command line argument to run_library_cli

CHANGELOG.md, setup.py, vivarium/core/engine.py
Previously, Engine expected a flow to be a flat dictionary with process
names as keys. This requires that processes have unique names, which is
not a general requirement of Vivarium (e.g. two cells can have processes
of the same name). This commit fixes this behavior to support nested
flows.
=> Make Engine Handle Flows with Nested Dictionaries

CHANGELOG.md, setup.py, vivarium/core/engine.py, vivarium/core/store.py
Instead of using `isinstance` to check whether a process is a step, we should use `Process.is_step()` since some processes don't inherit from `Step` but still override `is_step()` to return `True`.
This PR also adds an assertion to make sure that when Engine treats a process like a step, that process really is a step.
=> Replace isinstance(..., Step) with Process.is_step() calls

vivarium/composites/toys.py, vivarium/core/control.py, vivarium/core/engine.py, vivarium/core/store.py, vivarium/experiments/engine_tests.py, vivarium/experiments/test_profiler.py, vivarium/processes/division.py, vivarium/processes/meta_division.py
`Store.build_topology_views` allows Engine to expire and recache views upon a hierarchy update. This worked great from simulations such as `vivarium-ecoli`, which have infrequent hierarchy updates, but it leads to considerable slowdown for division-heavy simulation such as `tumor-tcell`. This PR attempts to improve the runtime for `tumor-tcell` found by @johnhickey22.
This PR introduces a new `test_hyperdivision` function to `engine_tests.py` which reproduced the high-division simulations and consequent slowdown. This was fixed by removing a line with `state = self` in `Store.schema_topology`, which was returning the entire agents branch for `division` processes that link to agents with the topology `{'agents_port': ('..', '..', 'agents')}`. This would result an enormous slowdown when …
=> expire and recache topology_views after Engine.apply_update

CHANGELOG.md, setup.py, vivarium/core/store.py
Division used the mother cell state as the default state and deep-merged the result of running the dividers into that default. This led to daughter cells getting molecules that were sent by the dividers to the other daughter.
Instead, we should use the result of running the dividers as the default daughter state. Then, we can deep-merge in any state provided by the meta-division process as part of the `_divide` update.
=> Use initial instead of mother state for division

CHANGELOG.md, vivarium/core/process.py, vivarium/core/store.py, vivarium/experiments/engine_tests.py
With this change, ports can be designated as output-only in a Process `ports_schema` by designating with with the special key `_output`. This helps reduce topology views when they are not needed, and lowers Vivarium overhead:
```
schema = {
'port1': {
'_output': True,
'A': {..},
'B': {..},
....
}
}
```
TODO before merge:
=> output-only ports

vivarium/core/composer.py
`Composite.merge` needed to be updated to work with the new `steps` and `flow` paradigm.
=> extend composite.merge to include steps and flows

vivarium/composites/toys.py, vivarium/core/engine.py, vivarium/experiments/engine_tests.py, vivarium/processes/toy_gillespie.py
In order to update Engine's processes iteratively we have to allow processes to hang on the `front`, and not be forced to update within the given interval. To do this, I separated `Engine.update` from a new method `Engine.run_for`. `Engine.update` completes all the processes within the provided interval, just as it had before. `Engine.run_for` can be called iteratively to advance the front up to the interval, but can leave processes hanging if its argument `force_complete=False`. The new method `Engine.complete()` forces all processes to complete at the current `global_time`.
Note:
- To get an `EngineProcess` that can handle multi-timestepping will require its `Process.calculate_timestep` to call a currently non-existent `Engine.next_timestep` method, which will return the time to the …
=> Engine.run_for allows iterative engine calls without completing.

CHANGELOG.md, setup.py, vivarium/core/engine.py, vivarium/experiments/store_api.py
This PR creates two new tests in store_api.py which currently fail. 
The first is `test_run_inserted_store` which produces an error `store at path ('p1',) does not have a topology_view` by creating a store and manually inserting a process using the API.
The second is similar to the first, but two processes are rewired after being created using store.connect. This results in a different error: `'ToyProcess' object is not subscriptable`
=> Store API tests which fail

CHANGELOG.md, setup.py, vivarium/core/process.py, vivarium/core/store.py
* Fixes #128: Raise an exception when a user-provided configuration specifies different dividers for the same variable.
* Fixes #129: When serializing a process, use its original parameters, without any changes that the subclass might have made.
I don't think there are really any breaking changes here. Technically the dividers exception changes behavior, but it's just raising an error on something users shouldn't have been doing anyway. Even if process parameters cannot be copied (e.g. are not serializable), no error is raised unless the user tries to serialize the process. If a process had non-serializable parameters, they wouldn't have been able to serialize before, so this is not a breaking change.
=> Safety improvements: Check that divider configs are consistent and use original parameters for serialization

vivarium/core/store.py
This corrects a bug found by @U8NWXD -- inserting a process with the `Store` api should not assume that the process's initial_state is used.
=> set_path with inserted process does not use process.initial_state()

vivarium/core/store.py
Consider the following tree:
```
a
/  \
b     c
/  \     \
d    e     f
```
The path `('e',)` from node `a` is invalid, but there is a path from `a` to `e` and `a` is not a leaf node. This PR corrects Store's error message to accurately describe cases like this.
=> Remove Reference to Leaf From No Path Error Msg

vivarium/core/process.py
We don't use the `Process.local_timestep()` function, so this PR removes it.
=> Remove Process.local_timestep()

vivarium/composites/toys.py, vivarium/core/engine.py, vivarium/core/process.py, vivarium/core/store.py, vivarium/experiments/bigraph_view.py, vivarium/experiments/engine_tests.py
This adds a new schema option for connecting a port to an entire subtree. To do this, the port in `ports_schema` can use `**`:
```
def ports_schema(self):
return {
'top': '**',
'other': {
'_default': 2.0
}
}
```
This port can connect at any point in the bigraph. To connect at the top, you can use a an empty path `()`:
```
topology = {
'top_view': {
'top': (),
'other': ('other',),
}
}
```
When viewed in `next_update` this gives the full subtree, include processes as tuples with their topology:
```
ipdb> pp top
{'agents': {'1': {'external': {'GLC': 10.0},
'internal': {'GLC': 0.0},
'membrane': 0.0,
'transport': (<vivarium.composites.toys.ToyTransport object at 0x110b6ea90>,
{'external': ('external',),
'internal': ('internal',)})}},
'environment': (<vivarium.composites.toys.ToyEnvironment …
```
=> View subtree with **

.github/CODEOWNERS, .github/workflows/docs.yml, .github/workflows/mypy.yml, .github/workflows/pylint.yml, .github/workflows/pytest.yml, AUTHORS.md
Fixes #142 by:
* Naming GitHub Actions workflows so we can require that certain workflows pass before PRs can be merged.
* Creating a CODEOWNERS file so that maintainers have to approve all PRs. See [GitHub's docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax) for syntax
repository.
=> Name workflows and create codeowners for permissions

vivarium/core/process.py
If a user creates a process whose constructor accepts parameters under a
customized name (e.g. `parameters` instead of `initial_parameters`),
serialization with `__setstate__` should still work. To support this,
make `__setstate__` pass parameters to the constructor as a positional,
not a keyword, argument.
repository.
=> Pass Parameters Positionally in __setstate__

vivarium/core/engine.py
I regret making `Engine.run_steps` private, since I think this should be one of the main methods for `Engine`. Making it public again before people start using the private method.
repository.
=> make Engine.run_steps public again

vivarium/core/composer.py, vivarium/core/engine.py, vivarium/core/serialize.py, vivarium/experiments/engine_tests.py
Initial_state was always handled separately from composites, which are dicts of processes, steps, topology, and flow. This PR adds `state` to `Composite`, which makes it sufficient to specify a full store hierarchy. 
This PR also adds the function arguments `processes`, `topology`, `steps`, `flow`, `state`, and `store` to `Composite` -- previously it only accepted a `config` dict with these arguments as keys. Function arguments are just a cleaner way of doing the same thing. `config` dicts are still compatible as the 1st positional argument to `Composite`.
repository.
=> initial_state added to Composite

setup.py, vivarium/core/engine.py, vivarium/processes/divide_condition.py, vivarium/processes/meta_division.py
Fix a couple bugs:
* In `divide_condition.py`, use a divider that sets the division variable to `False` instead of `0`. `0` worked because it is falsy, but the variable is really supposed to be a boolean.
* In `vivarium/core/engine.py`, our check for step-flow consistency did not correctly handle the case where steps are nested in sub-dicts. This PR fixes the check.
repository.
=> Fix divider and flow bugs

vivarium/core/engine.py
Passing `store` into `Engine` was not setting `initial_state`, now it does.
repository.
=> Store initial_state

CHANGELOG.md, setup.py, vivarium/core/process.py
In cases where parameters are large, users may want to save memory by preventing Process from saving a copy of the parameters. This PR adds an option to allow this. When using this option, the user must make sure that the parameters are not mutated.
repository.
=> Add _no_original_parameters config to Process

CHANGELOG.md, setup.py, vivarium/core/emitter.py
Some unassembled data might not have a 'time' variable -- this includes some large 'unique' states in vivarium-ecoli that need to get merged into a dict with ['bulk', 'listeners', 'time'] keys, which has time. Removing this requirement for a 'time' key from `get_history_data_db` recovers some lost 'unique' states.
repository.
=> `get_history_data_db` remove time key requirement

CHANGELOG.md, setup.py, vivarium/__init__.py, vivarium/core/engine.py, vivarium/core/process.py, vivarium/core/registry.py, vivarium/core/serialize.py, vivarium/core/serialize_test.py
Make our handling of serialization more structured and robust. Now, we create classes that inherit from `Serializer` to define serializers. These serializers each know what kinds of objects they can serialize and deserialize, so the `serialize_value` and `deserialize_value` functions can automatically find the correct serializer for a given object. We also throw an error if no serializer or multiple serializers are found for an object to make serialization more robust.
repository.
=> Make Serializers Robust and Structured

vivarium/core/engine.py, vivarium/core/store.py, vivarium/experiments/engine_tests.py
Previously it was necessary to override variable emits with a '_schema' value passed to the processes or the composite. This was confusing and complicated because it had to be directed through the processes' ports, rather than through the Store hierarchy.
`Store.toggle_emits` allows you to turn emits on/off with more ease. This method has args `emit` and `paths`. `emit` is a boolean True/False to turn the emit on or off. `paths` is a list of paths to toggle on/off -- all nodes below those paths will be set to the `emit` value.
This can be accessed through `Engine` with the `store_emit` keyword, which can be supplied with a dictionary that has `'on'`, `'off'` keys that map to a list of paths to turn on or off: 
```
sim= Engine(
composite=composite,
store_emit={
'on': [('path', '1',), …
```
=> Toggle emits on/off in Store

CHANGELOG.md, setup.py, vivarium/core/emitter.py
When passing a query to `get_history_data_db`, the `assembly_id` key was being removed when applying a projection in the DB. This PR adds it in, so it will always be retrieved with the documents.
repository.
=> project assembly_id when querying db

README.md
In an effort to make our PyPI project more obvious -- `vivarium-core` as opposed to `vivarium` -- I have move the set up instructions further up in the readme.
repository.
=> make PyPI name more prominent in readme

CHANGELOG.md, setup.py, vivarium/core/engine.py, vivarium/core/store.py, vivarium/experiments/engine_tests.py, vivarium/experiments/store_api.py
A new `store_schema` arg to `Engine` allows us to override schema directly. This includes state values, emits, etc. This replaces the `store_emit` argument introduced in #170, since the new `store_schema` dict can turn emits on/off more directly. A new check in `Store._apply_config` lets us use schema to set the emit values for all leaf nodes under a given branch, by setting the `_emit` schema of that branch node to `True` or `False`.
In the new `test_add_new_state`, this feature is demonstrated by adding an `extra` key to the agent state, and turning its emit to true:
```
new_schema = {'agents': {agent_id: {'extra': {'_emit': True, '_value': 1.0}}}}
experiment = Engine(
processes=composite.processes,
topology=composite.topology,
store_schema=new_schema,
)
```
As an example of how to set …
=> override schema directly in Engine

setup.py
There are a couple uses of pytest documented in #181, which make pytest a requirement. Currently users have to install it themselves to run Vivarium. This PR adds it to setup.py. 
repository.
=> add pytest to setup

vivarium/core/engine.py, vivarium/experiments/engine_tests.py
Floating-point errors were causing small timesteps to be incorrectly added to `Engine.global_time`, leading to ugly output with base save times. The following example had one process with `timestep=0.1`:
```
0.0: {'agents': {'1': {'external': {'GLC': 0.0}, 'internal': {'GLC': 0.0}}}},
0.1: {'agents': {'1': {'external': {'GLC': 0.0}, 'internal': {'GLC': 0.0}}}},
0.2: {'agents': {'1': {'external': {'GLC': 0.0}, 'internal': {'GLC': 0.0}}}},
0.30000000000000004: { 'agents': { '1': { 'external': {'GLC': 0.0},
'internal': {'GLC': 0.0}}}},
0.4: {'agents': {'1': {'external': {'GLC': 0.0}, 'internal': {'GLC': 0.0}}}},
0.5: {'agents': {'1': {'external': {'GLC': 0.0}, 'internal': {'GLC': 0.0}}}},
0.6: {'agents': {'1': {'external': {'GLC': 0.0}, 'internal': {'GLC': 0.0}}}},
0.7: {'agents': {'1': …
```
=> floating-point timestep precision

vivarium/core/emitter.py
Fixing a bug found while working on vivarium-ecoli. The `RAMEmitter.get_data(query)` was returning empty dicts for queries that did not exist. With this PR nothing is returned if the data does not exist. 
repository.
=> RAMEmitter only returns query if data exists

vivarium/core/composition.py, vivarium/core/engine.py, vivarium/core/process.py, vivarium/plots/topology.py, vivarium/processes/tree_mass.py
This fixes some bugs I found when working on topology plots for a Composite both before and after division. I noticed that after division, some Steps were missing from the topology plot. I tracked this down to incomplete passing of a composite's hierarchical updates to its steps -- while the engine was tracking the steps in `Engine.steps`, it wasn't being applied to the `composite['steps']` that had been passed into engine with `Engine(composite=composite)`. 
repository.
=> track composite updates in engine

vivarium/composites/toys.py, vivarium/core/process.py, vivarium/core/serialize_test.py
This change the process parameter to `timestep` from `time_step`. This change is to keep consistent with other parts of the codebase, such as `engine.py`. `time_step` as a process input parameter remains compatible, but is internal changed to `timestep`.
repository.
=> timestep instead of time_step

vivarium/core/engine.py, vivarium/experiments/engine_tests.py
make `global_time_precision` an `Engine` parameter instead of an `Engine.run_for()` keyword. This is more reproducible if we want to rerun a simulation.
repository.
=> make global_time_precision an Engine parameter

.pylintrc, CHANGELOG.md, setup.py, vivarium/core/engine.py
A previous PR pulled the calculation of which timestep to advance to the top level of the update loop, which meant the timesteps for quiet paths were being expressed even though they weren't being calculated or making updates. This was causing problems with combining processes with small time steps with processes with large time steps. 
The fix is to avoid updating the timestep if the process is not updating due to not meeting it's update condition in the current state. 
repository.
=> don't use timestep for quiet paths

.github/workflows/docs.yml, setup.py, vivarium/core/engine.py, vivarium/experiments/engine_tests.py
Make step execution order deterministic, even within execution layers.
repository.
=> Deterministic step execution order within layers

.github/workflows/docs.yml, CHANGELOG.md, vivarium/core/composition.py
In c5ce1b4, `initial_state` was removed from the list of allowed
experiment config keys to pass to `Engine`. This change was probably
made to avoid a clash between `initial_state` in the config dictionary
and the keyword argument, but the consequence is that initial states can
no longer be passed to many `composition.py` functions.
This commit restores `initial_state` to the list of allowed config keys
and avoids the clash by putting the keyword-arg `initial_state` into the
config dictionary.
repository.
=> Add initial_state to composition.py Engine keys

CHANGELOG.md, setup.py, vivarium/core/emitter.py
It's sometimes useful to pass additional filters when retrieving simulation data from the database, for example to retrieve only every 10th timepoint from long simulations. This PR adds a `filters` argument to `data_from_database()` to allow this.
repository.
=> Allow passing additional filters to data_from_database

CHANGELOG.md, setup.py, vivarium/__init__.py, vivarium/core/emitter.py, vivarium/core/engine.py, vivarium/core/store.py, vivarium/experiments/engine_tests.py, vivarium/library/dict_utils.py, vivarium/library/topology.py, vivarium/processes/toy_gillespie.py
This allows e.g. multiple parallel `Engine` instances to send emits to
the same destination, e.g. the same database. So long as they use the
same experiment IDs and have synchronized times, the emits will be
merged upon retrieval.
repository.
=> Support multiple emits for the same timestep

vivarium/core/composer.py, vivarium/library/topology.py
When a single process has multiple ports into a store holding a dictionary, running the `initial_state` method of the `Composite` yields a multi-update for the initial value of that store. This PR adds a flag to instead populate the store with the correct initial dictionary.
repository.
=> Prevent multi-updates in initial_state

CHANGELOG.md, setup.py, vivarium/core/serialize.py, vivarium/core/store.py
Fix a bug in `Store.apply_update` to correctly handle lists of `Quantity` objects.
repository.
=> Handle lists of Quantities in `Store.apply_update`

vivarium/core/process.py, vivarium/core/store.py
Parallel processes were not properly saving certain class attributes, including `_parallel`, causing them to be lost upon pickling during division.
Additionally, we were not properly ending parallel processes when deleting stores, causing a memory leak. 
Both of these issues are fixed in this PR.
repository.
=> Fix memory leak and parallel process division

doc/conf.py, vivarium/__init__.py, vivarium/core/emitter.py, vivarium/core/engine.py, vivarium/core/registry.py, vivarium/core/serialize.py, vivarium/core/serialize_test.py, vivarium/core/store.py, vivarium/experiments/engine_tests.py
Serialization of emitter data can make up a large portion of simulation runtimes, according to profiling data. 
PyMongo implements its serialization logic in C and has the ability to accept custom encoders via the [`TypeCodec` interface](https://pymongo.readthedocs.io/en/stable/examples/custom_type.html). Here, I modify the `Serializer` class to instantiate and return `TypeCodec` instances for serialization. 
When no document splitting is required, this PR nearly halves simulation time (running a simulation with a relatively large and complex emit). When document splitting is required at every timestep, the performance improvement drops to about 20%.
- Our [document-splitting algorithm](https://github.com/vivarium-collective/vivarium-core/blob/02b6bb51717e9d760cf425f851ff1b9064eb7590/vivar …
=> Optimize Serialization Using BSON C Extensions

vivarium/__init__.py, vivarium/core/emitter.py, vivarium/core/store.py, vivarium/library/topology.py
The `without` and `without_multi` functions are surprisingly slow. Creating a shallow copy of the dictionary and popping the desired keys is functionally equivalent but much faster.
I also removed a `pyplot` import that no longer seems to be necessary.
repository.
=> Optimize dictionary key removal

doc/reference/api/vivarium.core.serialize.rst, doc/requirements.txt, requirements.txt, vivarium/__init__.py, vivarium/core/emitter.py, vivarium/core/engine.py, vivarium/core/process.py, vivarium/core/registry.py, vivarium/core/serialize.py, vivarium/core/serialize_test.py, vivarium/core/store.py, vivarium/experiments/engine_tests.py
BSON has a hidden maximum serialized size of 2GB (refer to [this](https://github.com/mongodb/mongo-python-driver/blob/179efda31200b495beab6c2e94f365f5713aadc4/bson/buffer.c#L106)). In this PR, we switch to using the `orjson` package, which has no size limits and is generally faster than BSON anyways. Orjson also has the benefit of natively supporting Numpy arrays and types. 
An important caveat is `np.str_`. Orjson will complain if dictionary keys are of the type `np.str_` or if the data to serialize contains arrays with `np.str_` values. The latter case is handled by a fallback [Numpy array serializer](https://github.com/vivarium-collective/vivarium-core/blob/a8749ce3fd202b9d79c9a82f810e617ee3e6746a/vivarium/core/serialize.py#L104), but users must manually ensure that all dictionary keys …
=> Serialization fixes

requirements.txt, vivarium/core/emitter.py
Our default collection indices are out of date. This PR removes unused indices and implements the correct index for simulation time, which should improve performance for queries targeting specific time points or ranges.
repository.
=> Create Mongo index for simulation time

vivarium/core/emitter.py
The MongoDB documentation recommends that only a single `MongoClient` be created per application, taking advantage of connection pooling to reduce latency and the number of new connections ([refer to docs](https://www.mongodb.com/docs/manual/administration/connection-pool-overview/)). At the same time, PyMongo is not fork-safe and [strongly recommends](https://pymongo.readthedocs.io/en/stable/faq.html#using-pymongo-with-multiprocessing) that a new `MongoClient` be created for each child process. This PR strikes a balance between these guidelines by caching `MongoClient` instances by PID, only spawning a new instance if running under a new PID.  …
=> Create new MongoClient per OS process

setup.py, vivarium/core/emitter.py
A single MongoDB query is unable to fully saturate I/O throughput on Google Compute Engine. This PR creates helper methods to intelligently split large queries into smaller, approximately equal chunks that can be run in parallel on separate OS processes. The number of chunks can be manually tuned to reach I/O saturation for maximum performance.
This was made possible by a new compound index: `{experiment_id: 1, 'data.time': 1, _id: 1}`. This index fully covers the aggregation step in `get_data_chunks` and represents a marked improvement over using any single-key index for queries that specify ranges or values for `experiment_id` or `data.time`. Best of all, compound indices maintain the ability to [cover queries on prefixes](https://www.mongodb.com/docs/manual/core/index-compound/#prefixes …
=> Parallel queries

vivarium/core/emitter.py
This PR fixes crashes that occur when breaking down a large document results in a document that lacks the `data` key altogether.
repository.
=> Allow breakdown document to lack data key

CHANGELOG.md, doc/conf.py, doc/requirements.txt, requirements.txt, setup.py, vivarium/core/serialize.py, vivarium/library/units.py
pint version 0.20.1 changed the location of `Quantity` and `Unit`, which led to import errors for some vivarium users. This PR adds try/except statements where these are imported to make the imports come from the correct modules.
repository.
=> update pint imports for 0.20.1

CHANGELOG.md, setup.py, vivarium/core/serialize.py, vivarium/core/store.py
I was informed of an import error some users were experiencing by having the registries imported from the top-level vivarium module. Fixed by changing the `store.py` imports.
repository.
=> import registries from registry module to fix bug

CHANGELOG.md, setup.py, vivarium/composites/toys.py, vivarium/core/composition.py, vivarium/core/control.py, vivarium/core/emitter.py, vivarium/core/store.py, vivarium/experiments/store_api.py, vivarium/processes/alternator.py, vivarium/processes/burst.py, vivarium/processes/ecoli_shape_deriver.py, vivarium/processes/engulf.py, vivarium/processes/growth_rate.py, vivarium/processes/meta_division.py, vivarium/processes/remove.py, vivarium/processes/swap_processes.py, vivarium/processes/toy_gillespie.py, vivarium/processes/tree_mass.py
- Addresses some bugs in `emitter.py`
- [`DatabaseEmitter.write_emit`](https://github.com/vivarium-collective/vivarium-core/blob/a927c7abf943d02c6d9a9008dacd37b15a597caf/vivarium/core/emitter.py#L381C1-L381C1): Drop the `ObjectID` added by `insert_one` before chunking large docs
- [`get_history_data_db`](https://github.com/vivarium-collective/vivarium-core/blob/a927c7abf943d02c6d9a9008dacd37b15a597caf/vivarium/core/emitter.py#L626): `start_time` and `end_time` now work when `cpus=1`
- [`data_from_database`](https://github.com/vivarium-collective/vivarium-core/blob/a927c7abf943d02c6d9a9008dacd37b15a597caf/vivarium/core/emitter.py#L695C10-L695C10): Clarify to accept a `Database` instance and not a `MongoClient`
- Addresses #228 in `store.py`
- Ensures all tests return `None` by default …
=> Schema fix

CHANGELOG.md, vivarium/core/engine.py, vivarium/core/store.py, vivarium/library/dict_utils.py
This PR properly closes #228 by allowing Numpy arrays to be buried deep within ports schemas ([example for `_divider`](https://github.com/vivarium-collective/vivarium-core/blob/ab6346d369d9224e2df6945db74c143007246300/vivarium/core/engine.py#L1341-L1346)). Additionally, this fixes a bug I introduced in #233 which caused things like 0 and `np.zeros(10)` to be considered equivalent in ports schemas when they should not be.
To ensure that everything works as intended, I added [`test_numpy_schema_validation`](https://github.com/vivarium-collective/vivarium-core/blob/a0945835681e63d58bdbfc9d0b666e44dce0f4a4/vivarium/core/engine.py#L1242) to `engine.py`. …
=> Recursively compare schemas during validation

.github/workflows/pytest.yml, CHANGELOG.md, setup.py, vivarium/core/emitter.py, vivarium/experiments/hierarchy_composite_division.py, vivarium/experiments/large_experiment.py
Adding MongoDB to the test environment proved very straightforward thanks to [service containers](https://docs.github.com/en/actions/using-containerized-services/about-service-containers). I repurposed an existing script to test large emits, query capabilities, and manual insertion of documents. Along the way, I fixed three issues:
- `time` key was not being added to broken-down emits when `time` was 0
- Deleting configuration in `delete_experiment_from_database` failed when using multiple CPU processes
- Documents manually inserted using `data_to_database` were not retrievable by `data_from_database` unless a specific structure was adhered to
According to `pytest`, coverage of `emitter.py` went from 44% to 90% with this PR. Most of the remaining untested code is in the MongoDB Atlas …
=> Add tests for MongoDB and fix bugs

.pylintrc, CHANGELOG.md, vivarium/core/engine.py
Thanks to @pmendes for reporting this bug to me. The `emit_time` was showing some floating point rounding errors, which were not corrected by `global_time_precision`. This fix checks for `global_time_precision` and corrects the `emit_time` accordingly
repository.
=> correct emit_time for the global_time_precision

CHANGELOG.md, setup.py
I have heard reports that the `Quantity` import in `vivarium.library.units` is causing import errors. Trying to fix it with this PR.
repository.
=> fix Quantity import
