vivarium-collective/vivarium-core

setup.py, vivarium/core/composition.py, vivarium/core/experiment.py, vivarium/core/process.py
=> migrating latest changes from vivarium

.github/workflows/pytest.yml
Sets up GitHub Actions to run pytest
=> Setup continuous integration

vivarium/core/experiment.py
The key in ```experiment``` line 1489 should be ```path```. https://github.com/vivarium-collective/vivarium-core/blob/24f2586bbee74f2d5806c978e106d951af942e6c/vivarium/core/experiment.py#L1489
=> fix key in experiment update

vivarium/__init__.py, vivarium/core/composition.py, vivarium/core/experiment.py, vivarium/processes/divide_condition.py, vivarium/processes/meta_division.py
This adds a progress bar option for experiments, which updates during runtime. The function was adapted from : https://stackoverflow.com/questions/3173320/text-progress-bar-in-the-console. To turn it on pass ```progress_bar: True``` into the ```experiment_config```.
This is its current appearance:
=> progress bar

vivarium/core/composition.py, vivarium/core/control.py, vivarium/core/experiment.py, vivarium/core/process.py, vivarium/plots/agents_multigen.py, vivarium/processes/meta_division.py
This continues the work started on #20, by testing with ```vivarium-cell``` experiments.
=> more work on Control

vivarium/core/process.py
This adds a ```merge``` function to the ```Generator``` class, which allows configured processes and a topology to be added to an existing generator, and then merged with that generator's declared processes and topology within the ```Generator.generate()``` function. 
We have talked about this for a long time, but it was never quite obvious how to accomplish it -- I expect it will require additional use before it is perfected. Take this example case for the motivation -- Let's say with have a working ```ecoli_master``` generator, with many combined processes. Now we want to try out an additional process (say chemoreceptors), but without having to modify the original generator, and without having to copy/paste the entire generator declaration.  To do this, we can now use …
=> merge for generators

vivarium/__init__.py, vivarium/core/experiment.py, vivarium/core/registry.py, vivarium/plots/agents_multigen.py, vivarium/plots/topology.py, vivarium/processes/meta_division.py
I'm preparing some Jupyter notebooks for the build-a-cell modeling workshop. This branch includes changes that make it easier to access via Jupyter.
=> build-a-cell

vivarium/core/experiment.py, vivarium/plots/topology.py
This PR breaks up the methods for plotting a composite topology with networkX, so that graphs can be individually created without plotting.
=> Get network

vivarium/plots/simulation_output.py, vivarium/plots/topology.py
This PR includes some changes to the plots that improve visualizing simulation output in Jupyter notebooks.
=> Notebook improvements

vivarium/processes/molarity_deriver.py
I've been making some changes to a few derivers for the bioscrapeCOBRA composite and pushing to master. But since there might be a few more coming, this PR will group those commits.
=> update molarity derivers

vivarium/core/process.py, vivarium/plots/agents_multigen.py, vivarium/plots/simulation_output.py, vivarium/plots/topology.py, vivarium/processes/engulf.py
This PR tweaks some of the plotting functions to beautify output in the Jupyter notebooks being constructed for the Vivarium paper.
`plot_topology` has been overhauled to handle embedded hierarchies. It now accepts a 'coordinates' argument that allows users to manually set node locations. See https://github.com/vivarium-collective/vivarium-core/blob/401b8c74ca9b2c6dbbfee5a88fb70b9f01e8f6b3/vivarium/plots/topology.py#L571
=> Plotting improvements

vivarium/composites/toys.py, vivarium/core/process.py
This PR is for initial improvements to the Composite API, following the discussion today with @prismofeverything and @WilliamIX
Summary of changes:
* `AggregateComposer` is now `Combinator`. This can become the compiler-like object that builds composers and combines them.
* `Composite.merge` accepts a path that inserts the composite/process/topology into the full topology.
=> composite improvements

vivarium/experiments/profile_image.py, vivarium/experiments/profile_runtime.py
This PR adds `profile_image.py`, which I used to run profiling scans on Google Compute VMs with different numbers of CPUs:
=> profile VM images

CHANGELOG.md, setup.py, vivarium/core/composer.py, vivarium/library/dict_utils.py
Schema overrides should work for steps too, not just non-step processes
=> Override step schemas

.github/pull_request_template.md, CLA.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE.txt, README.md
* Add code of conduct
* Switch to Apache license and use CLA. The CLA is referenced in a PR template so that every new PR that gets opened will, by default, include a note agreeing to the CLA. I also noted in the contribution guidelines that opening a PR constitutes acceptance of the CLA.
* Add contributing guidelines
* Rearrange the README
=> Add community health files

AUTHORS.md, vivarium/core/engine.py, vivarium/core/store.py
In preparation for the release of 1.0, I'll making as many class methods private as possible. This reduces the exposed API and simplifies the interface for external users.
=> make methods private

CHANGELOG.md, setup.py
Create the 1.0.0 version
repository.
=> Bump version to 1.0.0

AUTHORS.md
Add recent contributors to the `AUTHORS.md` file
repository.
=> Add Mattheus, Sean, Michael, and William to AUTHORS.md

notebooks/Vivarium_interface_basics.ipynb
Minor reformatting of the tutorial notebook.
repository.
=> resize tutorial figures

vivarium/core/composer.py, vivarium/core/store.py
adds flows and steps to `Composite.generate_store`
repository.
=> Composite.generate_store flows and steps

CHANGELOG.md, setup.py, vivarium/core/process.py
Fixes #159. This PR will also be the v1.0.1 release.
repository.
=> Support serialization with original parameters from subclasses

doc/index.rst, doc/vale/styles/vocab.txt
Add a reference to the Vivarium paper in the documentation
repository.
=> add vivarium reference to docs

CHANGELOG.md, setup.py, vivarium/__init__.py
The injector process is really useful for testing, but we never registered it.
repository.
=> Register the Injector process

vivarium/core/serialize.py, vivarium/core/serialize_test.py
Update the units serializer to handle `nan` numbers.
repository.
=> Handle nan in units serializer

CHANGELOG.md, setup.py, vivarium/core/composer.py, vivarium/core/store.py
In preparation for the HARMONY workshop tomorrow I reran the vivarium_interface_basics notebook and got some bugs. This PR makes it work again, though these solutions are not good long-term. I will merge this in just for the workshop, but plan to come back and fix these issues.
repository.
=> changes to get notebook running all the way through

CHANGELOG.md, setup.py, vivarium/core/store.py
Increase the coverage of `Store.sources` information to include dividers and flows.
repository.
=> More comprehensive Store.sources

setup.py
This PR adds orjson to the requirements when installing from PyPI.
repository.
=> Add orjson to install requirements

CHANGELOG.md, vivarium/core/engine.py, vivarium/core/registry.py
=> Update networkx error msg for already deleted Step
